# Generated by Django 5.1.4 on 2025-01-08 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Datetime')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Datetime')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Datetime')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Datetime')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('salary', models.FloatField(verbose_name='Vacancy')),
                ('description', models.CharField(default=None, max_length=200, verbose_name='Description')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='my_app.city', verbose_name='City')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='my_app.profession', verbose_name='Profession')),
                ('tags', models.ManyToManyField(to='my_app.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
