# Generated by Django 5.1.4 on 2025-01-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
