# Generated by Django 5.1.4 on 2025-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(to='my_app.tag'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
