# Generated by Django 5.1.4 on 2025-01-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_city_create_city_update_profession_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='update',
            new_name='updated',
        ),
    ]
