# Generated by Django 5.1.4 on 2025-01-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_tag_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated Datetime'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated Datetime'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated Datetime'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated Datetime'),
        ),
    ]
